# Generated by Django 5.2 on 2025-04-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('operation', models.CharField(max_length=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
